config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users

  resources :events
  resources :users, only: [:show]
  resources :event_attendees, only: [:create]
  delete '/event_attendees', to: 'event_attendees#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees, source: :attendee

  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :date, presence: true

  scope :upcoming, -> { where('events.date >= ?', Date.today) }
  scope :past, -> { where('events.date < ?', Date.today) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :event_attendees, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendees, source: :attended_event

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  def create
    @event_attendee = EventAttendee.new(event_attendee_params)

    if @event_attendee.save
      redirect_back fallback_location: root_path, notice: 'Successfully joined event.'
    else  
      redirect_back fallback_location: root_path, status: :unprocessable_entity
    end
  end

  def destroy
    @event_attendee = EventAttendee.find_by(event_attendee_params)

    if @event_attendee.destroy
      redirect_to root_path, notice: 'Successfully left event.'
    else  
      redirect_back fallback_location: root_path, status: :unproccessable_entity
    end
  end

  private

  def event_attendee_params
    params.permit(:attendee_id, :attended_event_id)
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to event_path(@event.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.includes(:creator, :attendees).find(params[:id])
  end

  def index
    @upcoming_events = Event.upcoming.includes(:creator, :attendees)
    @past_events = Event.past.includes(:creator, :attendees)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to event_path(@event.id), notice: 'Successfully edited event.'
    else
      render :edit, status: :unproccessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])

    if @event.destroy
      redirect_to root_path, notice: 'Successfully deleted event.'
    else
      redirect_back fallback_location: root_path, status: :unproccessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :date)
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @created_events = User.find(params[:id]).created_events.includes(:creator, :attendees)
    @attended_events = User.find(params[:id]).attended_events.includes(:creator, :attendees)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/_event.html.erb
  <p>
    <b>Name:</b> <%= event.name %>
  </p>
  <p>
    <b>Description:</b> <%= event.description %>
  </p>
  <p>
    <b>Location:</b> <%= event.location %>
  </p>
  <p>
    <b>Date:</b> <%= event.date %>
  </p>
  <p>
    <b>Creator:</b> <%= event.creator.first_name + ' ' + event.creator.last_name %>
  </p>
  <p>
  <% unless current_page?(event_path(event.id))%>
    <a href="/events/<%= event.id %>">View Event</a>
  <% end %>
  <% if user_signed_in? && event.date > Date.today %>
    <% if event.attendees.include?(current_user) %>
          <%= form_with url: '/event_attendees', method: :delete do |form| %>
        <%= form.hidden_field :attendee_id, value: current_user.id %>
        <%= form.hidden_field :attended_event_id, value: event.id %>
        <%= form.submit value: 'Leave Event' %>
      <% end %>
    <% else %>  
      <%= form_with url: '/event_attendees' do |form| %>
        <%= form.hidden_field :attendee_id, value: current_user.id %>
        <%= form.hidden_field :attended_event_id, value: event.id %>
        <%= form.submit value: 'Join Event' %>
      <% end %>
    <% end %>
    <% if event.creator == current_user %>
      <%= form_with url: event_path(event.id), method: :delete do |form| %>
        <%= form.hidden_field :event_id, value: event.id %>
        <%= form.submit value: 'Delete Event'%>
      <% end %>
      <%= form_with url: edit_event_path(event.id), method: :get do |form| %>
        <%= form.hidden_field :event_id, value: event.id %>
        <%= form.submit value: 'Edit Event'%>
      <% end %>
    <% end %>
  <% end %>
  <br>
  <br>
</p>

app/views/events/_event_form.html.erb
<%= form_with model: @event do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </p>
  <p>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </p>
  <p>
    <%= form.submit%>
  </p>
<% end %>

app/views/events/edit.html.erb
<%= render partial: 'event_form', locals: { event: @event }%>

app/views/events/index.html.erb
<h1>Upcoming Events:</h1>
<% @upcoming_events.each do |event| %>
  <%= render partial: 'event', locals: { event: event } %>
<% end %>
<h1>Past Events:</h1>
<% @past_events.each do |event| %>
  <%= render partial: 'event', locals: { event: event } %>
<% end %>

app/views/events/new.html.erb
<%= render partial: 'event_form', locals: { event: @event }%>

app/views/events/show.html.erb
<%= render partial: 'event', locals: { event: @event }%>

app/views/layouts/_nav_bar.html.erb
  <a href="/events">Home</a>
  <% if user_signed_in? %>
    <a href="/events/new">Create Event</a>
    <a href="/users/sign_out">Sign out</a>
    <a href="/users/<%= current_user.id %>">Profile</a>
  <% else %>
    <a href="/users/sign_in">Sign in</a>
    <a href="/users/sign_up">Sign up</a>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/nav_bar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<% if @created_events.exists? %>
  <h2>Your created events: </h2>
  <% @created_events.each do |event| %>
    <%= render partial: 'events/event', locals: { event: event } %>
  <% end %>
<% else %>
  <p>You haven't created any events.</p>
<% end %>

<% if @attended_events.exists? %>
  <h2>Your upcoming attended events: </h2>
  <% @attended_events.each do |event| %>
    <% if event.date > Date.today %>
      <%= render partial: 'events/event', locals: { event: event } %>
    <% end %>
  <% end %>
  <h2>Your past attended events: </h2>
  <% @attended_events.each do |event| %>
    <% if event.date < Date.today %>
      <%= render partial: 'events/event', locals: { event: event } %>
    <% end %>
  <% end %>
<% else %>
  <p>You aren't attending any events.</p>
<% end %>